### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by serge-sans-paille** [man-group/sparrow#134]
There's no description of this package in the README, it would be helpful for an hypothetical packager..

**Comment by serge-sans-paille** [comment]
cc @SylvainCorlay / @JohanMabille

**Comment by JohanMabille** [comment]
Indeed, because we are missing the top level APIs to provide some example. I'll try to write something for next week (stating it's an early preview not ready for usage yet).

**Comment by SylvainCorlay** [comment]
Closing as fixed.

**Comment by Klaim** [comment]
Not sure it's a good idea to close this issue, there is still no examples in the ReadMe.

**Comment by DerThorsten** [comment]
I prefer not to add examples in the readme via markdown. They are not compiled and it's easy to add errors to these.
Its hard to maintain such examples because it's easy to forget to update them.

Instead, we should link https://man-group.github.io/sparrow/examples.html which is autogenerated and all the examples are compiled and run in the ci
